### ISSUE TITLE
Add Arctic Oscillation to datasets

### ISSUE THREAD

**Issue by jslanini** [usbr/PyForecast#16]
https://www.cpc.ncep.noaa.gov/products/precip/CWlink/daily_ao_index/ao.shtml

**Comment by tjrocha** [comment]
Arctic Oscillation added to pn-development branch. Also added SOI and MEI per USACE request.

https://www.esrl.noaa.gov/psd/enso/mei/
https://www.ncdc.noaa.gov/teleconnections/enso/indicators/soi/
