### ISSUE TITLE
Do we need a liability disclaimer?

### ISSUE THREAD

**Issue by jslanini** [usbr/PyForecast#19]
Should we add a disclaimer statement to the ReadMe/Wiki?

**Comment by tjrocha** [comment]
That would be a good idea. A standard one that @ktarbet and I have used for other projects is shown below. 

> The software as originally published constitutes a work of the United States Government and is not subject to domestic copyright protection under 17 USC ¤ 105. Subsequent contributions by members of the public, however, retain their original copyright.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by jslanini** [comment]
Thanks.  I added it to the readme file.
